menu:
  Home: /
  Archives: /archives
  About: /about
  RSS: /atom.xml
 
widgets:
# - search  #默认使用下面的swiftype搜索，也可以换做google(wen.lu)搜索，见search.ejs
- search_swiftype
- recent_posts
- category
- duoshuo_recent_comments  
- tagcloud
#- links

go_top: true

display_updated: true

# 如果在文章的 *.md 中使用 <!-- more -->，那么之后的内容不会在首页显示，而是显示 阅读全文 的链接，显示可以更改
excerpt_link: Read More

# 百度分享插件，bd_share.ejs > article.ejs
baidu_share: true

fancybox: true

google_analytics:
rss: /auto.xml
  
# 博客的社交分享，eg: 博客底部的两个图标
social:
# key weibo/twitter/google/github/stackoverflow/rss
# value url
# e.g github: https://github.com/DaiXiang
  github: https://github.com/seanlook
  segmentfault: http://segmentfault.com/u/seanlook
  google: mailto:seanlook7@gmail.com
  weibo: http://weibo.com/zhouxiaozhxi

# 显示文章目录
toc:
  article: false   ## show contents in article.
  aside: true     ## show contents in aside.
  
#站点统计footer.ejs，siteid,在获取统计代码的页面的地址栏上可以看到siteid=xxxx或从代码中提取(一般是一串数字)	
cnzz_analytics:
  enable: true
  siteid: 1253513173