categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts

updated: Updated

read more: Read More

#menu:
Home: Home
About: About
Archives: Archives
RSS: RSS